language: python
python: 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_31dfebda11a4_key -iv $encrypted_31dfebda11a4_iv
  -in config.creds.json.enc -out config.creds.json -d
install:
- pip install -r requirements.txt
script:
- python setup.py test
- python setup.py sdist bdist_wheel
deploy:
  password:
    secure: giLD8fU0fcjVG0Ht13m32d8Y/An2Utea6cEPE0AH+UxWpWh+LVZcLx8KrCGNGhup3wO40PsEa9mOc/sLuUUK0zj1Zb0JDhCANbiU4sPb1FXUtBAvSOjFU3UFPgL0OQQHV2zqOc41YT2TnR4LghCAKRhw3h2dJfgpuXmfTgHzcEP1H7u2malg8DTBgnSsqbY5fbKXOsAckRK+wSf+MdYLNCsddJpIZiUOBxGOGSQYToCLa0jByBJWm2N8FYRJrulaGHGaw1Z7QJ09IgMRRYXnYavCaYj22/zaezEM5qa3nE0tKaCXLdW86MyjYcIv1AsDpaIb8cJNj+qztgJzpALkN/VY9rdPgaLILrka7EHwFC4M8olXAph59CWEcACZV+LKvLg0Qe488hUp9f7s+fqgVNAleHgO6uuD7S56PfebGe3EQj242fn0WR94o2DG4h8qWKsNWjzmMSkUrKr1CaU2YQnooFqOQn18nULu8vd621RAyGkTdL4En7Fnq0MhzkVbWpSpFQCIusM0n4vnHTmqwjhbmGauC6Q668NPh0mjNb3Y5NMqc4RNiqHmlwyDviZn7zPd/zvazWZd45ysVz+1qziuTrtcwNrowAljHAPzoTGZcmKIGXNN0cM8HUN7ZaaFzJMFeoJe49/vkcPeUAWZBWyCUbHf6AU6c40LS936wSc=
deploy:
  provider: pypi
  user: "zamechek"
  password:
    secure: giLD8fU0fcjVG0Ht13m32d8Y/An2Utea6cEPE0AH+UxWpWh+LVZcLx8KrCGNGhup3wO40PsEa9mOc/sLuUUK0zj1Zb0JDhCANbiU4sPb1FXUtBAvSOjFU3UFPgL0OQQHV2zqOc41YT2TnR4LghCAKRhw3h2dJfgpuXmfTgHzcEP1H7u2malg8DTBgnSsqbY5fbKXOsAckRK+wSf+MdYLNCsddJpIZiUOBxGOGSQYToCLa0jByBJWm2N8FYRJrulaGHGaw1Z7QJ09IgMRRYXnYavCaYj22/zaezEM5qa3nE0tKaCXLdW86MyjYcIv1AsDpaIb8cJNj+qztgJzpALkN/VY9rdPgaLILrka7EHwFC4M8olXAph59CWEcACZV+LKvLg0Qe488hUp9f7s+fqgVNAleHgO6uuD7S56PfebGe3EQj242fn0WR94o2DG4h8qWKsNWjzmMSkUrKr1CaU2YQnooFqOQn18nULu8vd621RAyGkTdL4En7Fnq0MhzkVbWpSpFQCIusM0n4vnHTmqwjhbmGauC6Q668NPh0mjNb3Y5NMqc4RNiqHmlwyDviZn7zPd/zvazWZd45ysVz+1qziuTrtcwNrowAljHAPzoTGZcmKIGXNN0cM8HUN7ZaaFzJMFeoJe49/vkcPeUAWZBWyCUbHf6AU6c40LS936wSc=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true